### ISSUE TITLE
Request: To Make Program Work When Opened Through Chrome

### ISSUE THREAD

**Issue by dvl2014** [melotic/ThreateningYeti#14] opened 2020-03-27 07:06 UTC
I am requesting (if possible) for this program to work when a quiz/exam is open through google chrome. In my state at least, all universities who use lockdown browser only have it activated whenever the student opens the quiz/exam through the link available on their campus canvas.

**Comment by melotic** [comment] 2020-03-27 11:20
Duplicate of #2

**Closed by melotic** 2020-03-27 11:20 UTC
Labels: duplicate
